// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSB_Management.Data;

#nullable disable

namespace WSB_Management.Migrations
{
    [DbContext(typeof(WSBRacingDbContext))]
    [Migration("20250605155409_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:DisableMigrationsLocking", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WSB_Management.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Countryid")
                        .HasColumnType("bigint");

                    b.Property<long>("Customerid")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Countryid");

                    b.HasIndex("Customerid");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Bike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Brandid")
                        .HasColumnType("bigint");

                    b.Property<int?>("Ccm")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Brandid");

                    b.ToTable("bike", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Customerid")
                        .HasColumnType("bigint");

                    b.Property<string>("Firstname")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Customerid");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Longtxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shorttxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Cup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("cup", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Newsletter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Startnumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Validfrom")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerBike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Bikeid")
                        .HasColumnType("bigint");

                    b.Property<long>("Customerid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Bikeid");

                    b.HasIndex("Customerid");

                    b.ToTable("customer_bike", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerCup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Cupid")
                        .HasColumnType("bigint");

                    b.Property<long>("Customerid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Cupid");

                    b.HasIndex("Customerid");

                    b.ToTable("customer_cup", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Bikeid")
                        .HasColumnType("bigint");

                    b.Property<long>("Customerid")
                        .HasColumnType("bigint");

                    b.Property<long>("Eventid")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("Laptime")
                        .HasColumnType("time(6)");

                    b.Property<long>("Transponderid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Bikeid");

                    b.HasIndex("Customerid");

                    b.HasIndex("Eventid");

                    b.HasIndex("Transponderid");

                    b.ToTable("customer_event", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Validfrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Validuntil")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Vat")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Personals");
                });

            modelBuilder.Entity("WSB_Management.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WSB_Management.Models.Transponder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("transponder", (string)null);
                });

            modelBuilder.Entity("WSB_Management.Models.Address", b =>
                {
                    b.HasOne("WSB_Management.Models.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("Countryid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WSB_Management.Models.Bike", b =>
                {
                    b.HasOne("WSB_Management.Models.Brand", "Brand")
                        .WithMany("Bikes")
                        .HasForeignKey("Brandid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("WSB_Management.Models.Contact", b =>
                {
                    b.HasOne("WSB_Management.Models.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerBike", b =>
                {
                    b.HasOne("WSB_Management.Models.Bike", "Bike")
                        .WithMany("CustomerBikes")
                        .HasForeignKey("Bikeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Customer", "Customer")
                        .WithMany("CustomerBikes")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerCup", b =>
                {
                    b.HasOne("WSB_Management.Models.Cup", "Cup")
                        .WithMany("CustomerCups")
                        .HasForeignKey("Cupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Customer", "Customer")
                        .WithMany("CustomerCups")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cup");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WSB_Management.Models.CustomerEvent", b =>
                {
                    b.HasOne("WSB_Management.Models.Bike", "Bike")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Bikeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Customer", "Customer")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Event", "Event")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSB_Management.Models.Transponder", "Transponder")
                        .WithMany("CustomerEvents")
                        .HasForeignKey("Transponderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Customer");

                    b.Navigation("Event");

                    b.Navigation("Transponder");
                });

            modelBuilder.Entity("WSB_Management.Models.Bike", b =>
                {
                    b.Navigation("CustomerBikes");

                    b.Navigation("CustomerEvents");
                });

            modelBuilder.Entity("WSB_Management.Models.Brand", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("WSB_Management.Models.Country", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("WSB_Management.Models.Cup", b =>
                {
                    b.Navigation("CustomerCups");
                });

            modelBuilder.Entity("WSB_Management.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("CustomerBikes");

                    b.Navigation("CustomerCups");

                    b.Navigation("CustomerEvents");
                });

            modelBuilder.Entity("WSB_Management.Models.Event", b =>
                {
                    b.Navigation("CustomerEvents");
                });

            modelBuilder.Entity("WSB_Management.Models.Transponder", b =>
                {
                    b.Navigation("CustomerEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
